E2E test script and workflow changes. (#294)
- Create the IoT Hub and DPS at the suite level so that they are reused
  for all runs in the suite. This is because ARM is buggy and has
  various issues that make creating a new IoT Hub and DPS for every test
  untenable:

  - `az iot hub create` never completes even though the IoT Hub gets created
    just fine, because the async operation remains in "Running" state.

  - `az iot hub device-identity create` internally lists all hubs in the RG
    to discover the hub it's creating a device identity in, but this query
    randomly decides to return no Hubs at all in the RG. Forcing it to retry
    eventually causes it to return the Hub, but only for some tests.
    In other words, it can be simultaneously the case that one test sees
    Hubs in the RG and another doesn't.

  So this change refactors the e2e-tests.sh into multiple scripts for
  suite and test operations.

  To solve the problem of `az iot hub list` returning no Hubs, this change
  changes the `az iot hub device-identity {create,delete}` invocations to use
  `--login $iot_hub_connection_string` instead of `--hub-name $hub_name`.
  `az iot hub device-identity {create,delete}` don't try to list all Hubs
  when `--login` is provided.

- Include the branch name in the common resource name since the scheduled runs
  run against both main and release/1.2, so they need to use
  different resource names to avoid stepping on each other.

- Fix RedHat 8 package makefile target to derive the correct name for
  the aziot-keys OpenSSL engine.

- Fix RedHat 8 test runs to calculate the correct package artifact name,
  ie the one specified in packages.yaml

- Update VM images for E2E tests to the latest. The previous images would
  sometimes not come back after installing updates and rebooting, for
  unknown reason.

- `az iot hub create` now supports `--tags`, so the IoT Hub can be tagged at
  creation time instead of afterwards, removing the risk of leaking it.

- Change the VM image query samples to print the image URN, since that is what
  needs to be copied into the `vm_image` script variable.

- Switch to writing super-config and running `aziotctl config apply`
  instead of writing the individual services' configs.

- Enforce `az vm create` creates a Basic SKU public IP address for the VM.
  This is currently the default but `az vm create` was printing a warning that
  it will default to Standard in the future, which we don't need.

- Enforce time limits on the job steps since the default timeout of
  six hours is unnecessarily long.

- Limit parallelism to 10 for the manual workflow too.

diff --git a/.github/workflows/e2e-tests-manual.yaml b/.github/workflows/e2e-tests-manual.yaml
--- a/.github/workflows/e2e-tests-manual.yaml
+++ b/.github/workflows/e2e-tests-manual.yaml
@@ -1,6 +1,11 @@
 # Used to run the E2E tests against a branch of your choice from the github.com UI.
 #
-# DEVNOTE: Keep in sync with e2e-tests-scheduled.yaml
+# DEVNOTE:
+#
+# Keep `jobs` in sync with e2e-tests-scheduled.yaml. Differences are:
+#
+# - manual has `on: workflow_dispatch` while scheduled has `on: schedule`
+# - manual uses `github.event.inputs` for the branch while scheduled uses `strategy.matrix`
 
 name: 'e2e-tests-manual'
 
@@ -11,7 +16,29 @@ on:
         default: 'main'
 
 jobs:
-  e2e-tests:
+  suite-setup:
+    runs-on: 'ubuntu-18.04'
+
+    steps:
+    - uses: 'actions/checkout@v1'
+      with:
+        ref: "${{ github.event.inputs.branch }}"
+
+    - name: 'Run'
+      run: |
+        timeout 10m ./ci/e2e-tests/suite-setup.sh
+      env:
+        BRANCH: "${{ github.event.inputs.branch }}"
+
+        AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+        AZURE_USERNAME: "${{ secrets.AZURE_USERNAME }}"
+        AZURE_PASSWORD: "${{ secrets.AZURE_PASSWORD }}"
+        AZURE_RESOURCE_GROUP_NAME: "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
+        AZURE_LOCATION: "${{ secrets.AZURE_LOCATION }}"
+
+  test-run:
+    needs: 'suite-setup'
+
     runs-on: 'ubuntu-18.04'
 
     strategy:
@@ -32,6 +59,8 @@ jobs:
         - 'dps-symmetric-key'
         - 'dps-x509'
 
+      max-parallel: 10
+
     steps:
     - uses: 'actions/checkout@v1'
       with:
@@ -39,7 +68,8 @@ jobs:
 
     - name: 'Run'
       run: |
-        ./ci/e2e-tests.sh ${{ matrix.test_name }}
+        timeout 15m ./ci/e2e-tests/test-run.sh '${{ matrix.test_name }}' &&
+        timeout 5m ./ci/e2e-tests/test-cleanup.sh '${{ matrix.test_name }}'
       env:
         BRANCH: "${{ github.events.input.branch }}"
 
@@ -52,3 +82,66 @@ jobs:
         AZURE_LOCATION: "${{ secrets.AZURE_LOCATION }}"
 
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+
+    - name: 'Clean up on failure'
+      run: |
+        timeout 5m ./ci/e2e-tests/test-cleanup.sh ${{ matrix.test_name }}
+        exit 1 # Force the workflow to fail even if this step succeeds
+      if: "${{ failure() }}"
+      env:
+        BRANCH: "${{ github.event.inputs.branch }}"
+
+        OS: "${{ matrix.os }}"
+
+        AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+        AZURE_USERNAME: "${{ secrets.AZURE_USERNAME }}"
+        AZURE_PASSWORD: "${{ secrets.AZURE_PASSWORD }}"
+        AZURE_RESOURCE_GROUP_NAME: "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
+        AZURE_LOCATION: "${{ secrets.AZURE_LOCATION }}"
+
+  suite-cleanup:
+    needs: 'test-run'
+    if: "${{ success() }}"
+
+    runs-on: 'ubuntu-18.04'
+
+    steps:
+    - uses: 'actions/checkout@v1'
+      with:
+        ref: "${{ github.event.inputs.branch }}"
+
+    - name: 'Clean up'
+      run: |
+        timeout 5m ./ci/e2e-tests/suite-cleanup.sh
+      env:
+        BRANCH: "${{ github.event.inputs.branch }}"
+
+        AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+        AZURE_USERNAME: "${{ secrets.AZURE_USERNAME }}"
+        AZURE_PASSWORD: "${{ secrets.AZURE_PASSWORD }}"
+        AZURE_RESOURCE_GROUP_NAME: "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
+        AZURE_LOCATION: "${{ secrets.AZURE_LOCATION }}"
+
+  suite-cleanup-fail:
+    needs: 'test-run'
+    if: "${{ failure() }}"
+
+    runs-on: 'ubuntu-18.04'
+
+    steps:
+    - uses: 'actions/checkout@v1'
+      with:
+        ref: "${{ github.event.inputs.branch }}"
+
+    - name: 'Clean up on failure'
+      run: |
+        timeout 5m ./ci/e2e-tests/suite-cleanup.sh
+        exit 1 # Force the workflow to fail even if this step succeeds
+      env:
+        BRANCH: "${{ github.event.inputs.branch }}"
+
+        AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+        AZURE_USERNAME: "${{ secrets.AZURE_USERNAME }}"
+        AZURE_PASSWORD: "${{ secrets.AZURE_PASSWORD }}"
+        AZURE_RESOURCE_GROUP_NAME: "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
+        AZURE_LOCATION: "${{ secrets.AZURE_LOCATION }}"
